######################################################################
# Automatically generated by qmake (2.01a) Mon Jan 27 11:18:53 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h passwordedit.h
SOURCES += mainwindow.cc passwordedit.cc test.cc
