######################################################################
# Automatically generated by qmake (2.01a) Wed Feb 5 12:20:55 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h passwordedit.h
SOURCES += mainwindow.cpp passwordedit.cpp test.cpp
