######################################################################
# Automatically generated by qmake (2.01a) Wed Feb 5 12:20:27 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += main_window.h
SOURCES += main_window.cpp test3.cpp
