######################################################################
# Automatically generated by qmake (2.01a) Wed Feb 5 12:20:39 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += gauge.h
SOURCES += gauge.cpp testgauge.cpp
