######################################################################
# Automatically generated by qmake (2.01a) Mon Jan 27 11:20:37 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += gauge.h
SOURCES += gauge.cc testgauge.cc
